language: go

sudo: false

go:
  - "1.13"

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi
  - git clone https://github.com/hashcloak/Meson /tmp/Meson && cd /tmp/Meson && make up
  - docker run --rm
    -v `pwd`:/client
    --network nonvoting_testnet_nonvoting_test_net
    -v /tmp/gopath-pkg:/go/pkg
    -w /client
    golang:buster
    /bin/bash -c "GORACE=history_size=7 go test -race"

cache:
  directories:
    - $GOPATH/pkg/mod
