language: go

go:
  - "1.13"

before_install:
  - docker swarm init

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi
  - git clone https://github.com/hashcloak/Meson /tmp/Meson && cd /tmp/Meson
  - |
    if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]]; then
      TEST_COMMIT=$TRAVIS_PULL_REQUEST_SHA make tests
    else
      TEST_COMMIT=$TRAVIS_COMMIT make tests
    fi

cache:
  directories:
    - $GOPATH