language: go

sudo: false

go:
  - "1.13"

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi
  - go test ./pkg/*
cache:
  directories:
    - $GOPATH/pkg/mod
