language: go

go:
  - "1.13"

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi
  - |
    git clone https://github.com/hashcloak/Meson-plugin /tmp/meson-plugin
    cd /tmp/meson-plugin
    git checkout $TESTNET_COMMIT
    make testnet
    cd -
  - |
    go run ./integration/tests.go \
    -ldflags "-X github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/server/internal/pki.WarpedEpoch=true" \
    -c /tmp/meson-testnet/client.toml \
    -k /tmp/meson-testnet/provider-0 \
    -pk $TEST_PKS_ETHEREUM

cache:
  directories:
    - $GOPATH
